name: Build#3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
          msbuild-architecture: x64  # Change to x64 or remove this line

      - name: Install WebView2 runtime
        run: |
          iwr https://go.microsoft.com/fwlink/p/?LinkId=2124703 -OutFile MicrosoftEdgeWebview2Setup.exe
          Start-Process .\MicrosoftEdgeWebview2Setup.exe -ArgumentList "/silent /install" -Wait

      - name: Install Rust with rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: rustfmt, clippy

      - name: Install Node.js dependencies
        run: |
          npm install -g @tauri-apps/cli
          npm install -g pnpm          

      - name: Install project dependencies
        run: pnpm install
        
      - name: Resolve path
        run: |
          [System.IO.Path]::GetFullPath(".\apps\desktop\src-tauri\..\out")
    
      - name: Build the Tauri app
        run: |
          Start-Process PowerShell -Verb RunAs -ArgumentList "cd apps/desktop; pnpm tauri build"
        shell: pwsh

      - name: Upload archived build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-app
          # This path should be updated to the path for the build artifacts on the GitHub runner
          path: ./apps/desktop/src-tauri/target/release/bundle
